version: '3.7'

services:
  postgres:
    image: postgres:14.2
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: as!123
      POSTGRES_DB: as
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - postgres_data:/var/lib/postgresql/data
    networks:
      - as-network
  service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - '3333:3333'
    networks:
      - as-network
    depends_on:
      - postgres
networks:
  as-network:
volumes:
  node_modules:
  postgres_data:
